import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/navigation/nav";
import { ThemeProvider } from "@/components/providers/theme-provider"
import Toaster from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
  profile: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body

      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="px-6 md:px-12 max-w-8xl mx-auto flex-grow">
            <Nav />
            <Toaster />
            {children}
          </div>

        </ThemeProvider>
        {/* {isAdmin && profile} */}
      </body>
    </html>
  );
}
